//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wfiplib.WSautentificar {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccesoUser", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class AccesoUser : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private wfiplib.WSautentificar.DetalleAcceso[] ConsultaAccesoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public wfiplib.WSautentificar.DetalleAcceso[] ConsultaAcceso {
            get {
                return this.ConsultaAccesoField;
            }
            set {
                if ((object.ReferenceEquals(this.ConsultaAccesoField, value) != true)) {
                    this.ConsultaAccesoField = value;
                    this.RaisePropertyChanged("ConsultaAcceso");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DetalleAcceso", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class DetalleAcceso : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int usuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tokenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int usuario {
            get {
                return this.usuarioField;
            }
            set {
                if ((this.usuarioField.Equals(value) != true)) {
                    this.usuarioField = value;
                    this.RaisePropertyChanged("usuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string token {
            get {
                return this.tokenField;
            }
            set {
                if ((object.ReferenceEquals(this.tokenField, value) != true)) {
                    this.tokenField = value;
                    this.RaisePropertyChanged("token");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConsultasUsuaio", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ConsultasUsuaio : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private wfiplib.WSautentificar.DetalleUsuario[] consultaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public wfiplib.WSautentificar.DetalleUsuario[] consulta {
            get {
                return this.consultaField;
            }
            set {
                if ((object.ReferenceEquals(this.consultaField, value) != true)) {
                    this.consultaField = value;
                    this.RaisePropertyChanged("consulta");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DetalleUsuario", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class DetalleUsuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClaveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContraseñaField;
        
        private int IdEstadoField;
        
        private int IdRolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RolNombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaConectadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaRegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaCambioClaveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoField;
        
        private bool ConectadoField;
        
        private bool ActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RolAccesoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreEmpresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RutaField;
        
        private int salidaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdUsuario {
            get {
                return this.IdUsuarioField;
            }
            set {
                if ((this.IdUsuarioField.Equals(value) != true)) {
                    this.IdUsuarioField = value;
                    this.RaisePropertyChanged("IdUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Clave {
            get {
                return this.ClaveField;
            }
            set {
                if ((object.ReferenceEquals(this.ClaveField, value) != true)) {
                    this.ClaveField = value;
                    this.RaisePropertyChanged("Clave");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Contraseña {
            get {
                return this.ContraseñaField;
            }
            set {
                if ((object.ReferenceEquals(this.ContraseñaField, value) != true)) {
                    this.ContraseñaField = value;
                    this.RaisePropertyChanged("Contraseña");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int IdEstado {
            get {
                return this.IdEstadoField;
            }
            set {
                if ((this.IdEstadoField.Equals(value) != true)) {
                    this.IdEstadoField = value;
                    this.RaisePropertyChanged("IdEstado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int IdRol {
            get {
                return this.IdRolField;
            }
            set {
                if ((this.IdRolField.Equals(value) != true)) {
                    this.IdRolField = value;
                    this.RaisePropertyChanged("IdRol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string RolNombre {
            get {
                return this.RolNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.RolNombreField, value) != true)) {
                    this.RolNombreField = value;
                    this.RaisePropertyChanged("RolNombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string FechaConectado {
            get {
                return this.FechaConectadoField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaConectadoField, value) != true)) {
                    this.FechaConectadoField = value;
                    this.RaisePropertyChanged("FechaConectado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string FechaRegistro {
            get {
                return this.FechaRegistroField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaRegistroField, value) != true)) {
                    this.FechaRegistroField = value;
                    this.RaisePropertyChanged("FechaRegistro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string FechaCambioClave {
            get {
                return this.FechaCambioClaveField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaCambioClaveField, value) != true)) {
                    this.FechaCambioClaveField = value;
                    this.RaisePropertyChanged("FechaCambioClave");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string Correo {
            get {
                return this.CorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoField, value) != true)) {
                    this.CorreoField = value;
                    this.RaisePropertyChanged("Correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public bool Conectado {
            get {
                return this.ConectadoField;
            }
            set {
                if ((this.ConectadoField.Equals(value) != true)) {
                    this.ConectadoField = value;
                    this.RaisePropertyChanged("Conectado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public bool Activo {
            get {
                return this.ActivoField;
            }
            set {
                if ((this.ActivoField.Equals(value) != true)) {
                    this.ActivoField = value;
                    this.RaisePropertyChanged("Activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string RolAcceso {
            get {
                return this.RolAccesoField;
            }
            set {
                if ((object.ReferenceEquals(this.RolAccesoField, value) != true)) {
                    this.RolAccesoField = value;
                    this.RaisePropertyChanged("RolAcceso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string NombreEmpresa {
            get {
                return this.NombreEmpresaField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreEmpresaField, value) != true)) {
                    this.NombreEmpresaField = value;
                    this.RaisePropertyChanged("NombreEmpresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string Ruta {
            get {
                return this.RutaField;
            }
            set {
                if ((object.ReferenceEquals(this.RutaField, value) != true)) {
                    this.RutaField = value;
                    this.RaisePropertyChanged("Ruta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=17)]
        public int salida {
            get {
                return this.salidaField;
            }
            set {
                if ((this.salidaField.Equals(value) != true)) {
                    this.salidaField = value;
                    this.RaisePropertyChanged("salida");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSautentificar.AutentificarSoap")]
    public interface AutentificarSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento token del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AccesoAP", ReplyAction="*")]
        wfiplib.WSautentificar.AccesoAPResponse AccesoAP(wfiplib.WSautentificar.AccesoAPRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento token del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CerrarSesionAP", ReplyAction="*")]
        wfiplib.WSautentificar.CerrarSesionAPResponse CerrarSesionAP(wfiplib.WSautentificar.CerrarSesionAPRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento clave del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SeleccionarValidarAcceso", ReplyAction="*")]
        wfiplib.WSautentificar.SeleccionarValidarAccesoResponse SeleccionarValidarAcceso(wfiplib.WSautentificar.SeleccionarValidarAccesoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AccesoAPRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AccesoAP", Namespace="http://tempuri.org/", Order=0)]
        public wfiplib.WSautentificar.AccesoAPRequestBody Body;
        
        public AccesoAPRequest() {
        }
        
        public AccesoAPRequest(wfiplib.WSautentificar.AccesoAPRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AccesoAPRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int IdAplicacion;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int IdUsuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string token;
        
        public AccesoAPRequestBody() {
        }
        
        public AccesoAPRequestBody(int IdAplicacion, int IdUsuario, string token) {
            this.IdAplicacion = IdAplicacion;
            this.IdUsuario = IdUsuario;
            this.token = token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AccesoAPResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AccesoAPResponse", Namespace="http://tempuri.org/", Order=0)]
        public wfiplib.WSautentificar.AccesoAPResponseBody Body;
        
        public AccesoAPResponse() {
        }
        
        public AccesoAPResponse(wfiplib.WSautentificar.AccesoAPResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AccesoAPResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public wfiplib.WSautentificar.AccesoUser AccesoAPResult;
        
        public AccesoAPResponseBody() {
        }
        
        public AccesoAPResponseBody(wfiplib.WSautentificar.AccesoUser AccesoAPResult) {
            this.AccesoAPResult = AccesoAPResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CerrarSesionAPRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CerrarSesionAP", Namespace="http://tempuri.org/", Order=0)]
        public wfiplib.WSautentificar.CerrarSesionAPRequestBody Body;
        
        public CerrarSesionAPRequest() {
        }
        
        public CerrarSesionAPRequest(wfiplib.WSautentificar.CerrarSesionAPRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CerrarSesionAPRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string token;
        
        public CerrarSesionAPRequestBody() {
        }
        
        public CerrarSesionAPRequestBody(string token) {
            this.token = token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CerrarSesionAPResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CerrarSesionAPResponse", Namespace="http://tempuri.org/", Order=0)]
        public wfiplib.WSautentificar.CerrarSesionAPResponseBody Body;
        
        public CerrarSesionAPResponse() {
        }
        
        public CerrarSesionAPResponse(wfiplib.WSautentificar.CerrarSesionAPResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CerrarSesionAPResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public wfiplib.WSautentificar.AccesoUser CerrarSesionAPResult;
        
        public CerrarSesionAPResponseBody() {
        }
        
        public CerrarSesionAPResponseBody(wfiplib.WSautentificar.AccesoUser CerrarSesionAPResult) {
            this.CerrarSesionAPResult = CerrarSesionAPResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SeleccionarValidarAccesoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SeleccionarValidarAcceso", Namespace="http://tempuri.org/", Order=0)]
        public wfiplib.WSautentificar.SeleccionarValidarAccesoRequestBody Body;
        
        public SeleccionarValidarAccesoRequest() {
        }
        
        public SeleccionarValidarAccesoRequest(wfiplib.WSautentificar.SeleccionarValidarAccesoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SeleccionarValidarAccesoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string clave;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string contra;
        
        public SeleccionarValidarAccesoRequestBody() {
        }
        
        public SeleccionarValidarAccesoRequestBody(string clave, string contra) {
            this.clave = clave;
            this.contra = contra;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SeleccionarValidarAccesoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SeleccionarValidarAccesoResponse", Namespace="http://tempuri.org/", Order=0)]
        public wfiplib.WSautentificar.SeleccionarValidarAccesoResponseBody Body;
        
        public SeleccionarValidarAccesoResponse() {
        }
        
        public SeleccionarValidarAccesoResponse(wfiplib.WSautentificar.SeleccionarValidarAccesoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SeleccionarValidarAccesoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public wfiplib.WSautentificar.ConsultasUsuaio SeleccionarValidarAccesoResult;
        
        public SeleccionarValidarAccesoResponseBody() {
        }
        
        public SeleccionarValidarAccesoResponseBody(wfiplib.WSautentificar.ConsultasUsuaio SeleccionarValidarAccesoResult) {
            this.SeleccionarValidarAccesoResult = SeleccionarValidarAccesoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AutentificarSoapChannel : wfiplib.WSautentificar.AutentificarSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AutentificarSoapClient : System.ServiceModel.ClientBase<wfiplib.WSautentificar.AutentificarSoap>, wfiplib.WSautentificar.AutentificarSoap {
        
        public AutentificarSoapClient() {
        }
        
        public AutentificarSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AutentificarSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AutentificarSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AutentificarSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        wfiplib.WSautentificar.AccesoAPResponse wfiplib.WSautentificar.AutentificarSoap.AccesoAP(wfiplib.WSautentificar.AccesoAPRequest request) {
            return base.Channel.AccesoAP(request);
        }
        
        public wfiplib.WSautentificar.AccesoUser AccesoAP(int IdAplicacion, int IdUsuario, string token) {
            wfiplib.WSautentificar.AccesoAPRequest inValue = new wfiplib.WSautentificar.AccesoAPRequest();
            inValue.Body = new wfiplib.WSautentificar.AccesoAPRequestBody();
            inValue.Body.IdAplicacion = IdAplicacion;
            inValue.Body.IdUsuario = IdUsuario;
            inValue.Body.token = token;
            wfiplib.WSautentificar.AccesoAPResponse retVal = ((wfiplib.WSautentificar.AutentificarSoap)(this)).AccesoAP(inValue);
            return retVal.Body.AccesoAPResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        wfiplib.WSautentificar.CerrarSesionAPResponse wfiplib.WSautentificar.AutentificarSoap.CerrarSesionAP(wfiplib.WSautentificar.CerrarSesionAPRequest request) {
            return base.Channel.CerrarSesionAP(request);
        }
        
        public wfiplib.WSautentificar.AccesoUser CerrarSesionAP(string token) {
            wfiplib.WSautentificar.CerrarSesionAPRequest inValue = new wfiplib.WSautentificar.CerrarSesionAPRequest();
            inValue.Body = new wfiplib.WSautentificar.CerrarSesionAPRequestBody();
            inValue.Body.token = token;
            wfiplib.WSautentificar.CerrarSesionAPResponse retVal = ((wfiplib.WSautentificar.AutentificarSoap)(this)).CerrarSesionAP(inValue);
            return retVal.Body.CerrarSesionAPResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        wfiplib.WSautentificar.SeleccionarValidarAccesoResponse wfiplib.WSautentificar.AutentificarSoap.SeleccionarValidarAcceso(wfiplib.WSautentificar.SeleccionarValidarAccesoRequest request) {
            return base.Channel.SeleccionarValidarAcceso(request);
        }
        
        public wfiplib.WSautentificar.ConsultasUsuaio SeleccionarValidarAcceso(string clave, string contra) {
            wfiplib.WSautentificar.SeleccionarValidarAccesoRequest inValue = new wfiplib.WSautentificar.SeleccionarValidarAccesoRequest();
            inValue.Body = new wfiplib.WSautentificar.SeleccionarValidarAccesoRequestBody();
            inValue.Body.clave = clave;
            inValue.Body.contra = contra;
            wfiplib.WSautentificar.SeleccionarValidarAccesoResponse retVal = ((wfiplib.WSautentificar.AutentificarSoap)(this)).SeleccionarValidarAcceso(inValue);
            return retVal.Body.SeleccionarValidarAccesoResult;
        }
    }
}
