<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Tramite.aspx.cs" Inherits="wfip.Mtto.Tramite" %>

<%@ Register Assembly="AjaxControlToolkit" Namespace="AjaxControlToolkit" TagPrefix="ajaxToolkit" %>

<%@ Register src="Menu1.ascx" tagname="Menu1" tagprefix="uc1" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Mantenimiento</title>
    <link href="Estilos.css" rel="stylesheet" />
    <script>
        function ConfirmarProceso(mensaje) {
            var confirm_value = document.createElement("INPUT");
            confirm_value.type = "hidden";
            confirm_value.name = "confirm_value";
            if (confirm(mensaje)) {
                confirm_value.value = "Yes";
            } else {
                confirm_value.value = "No";
            }
            document.forms[0].appendChild(confirm_value);
        }
        function setBodyHeightToContentHeight() {
            document.body.style.height  = Math.max(150, 60)+"px";
            document.body.style.width =  Math.max(350,60)+"px";
        }

       setBodyHeightToContentHeight(); 
    </script>
</head>
<body>
    <form id="form1" runat="server">
        <asp:ScriptManager ID="ScripManager1" runat="server"></asp:ScriptManager>
        <div>
            
            <uc1:Menu1 ID="Menu11" runat="server" />
            
            <h1>Trámites</h1>

            <asp:Panel ID="PnlDetalleBitacora" runat="server" Visible="false" style="z-index: 100; top: 10px; left: 40%; border:2px solid green; background-color: white; cursor: move">
                <center><asp:Button ID="BtnCerrar" runat="server" Text="Cerrar" OnClick="BtnCerrar_Click" /></center>
                <br /><br />
                <asp:DetailsView ID="DVDetalleBitacora" runat="server" AutoGenerateRows="false" AllowPaging="true" DataKeyNames="Id" 
                    FieldHeaderStyle-BackColor="LightGray" 
                    FieldHeaderStyle-Wrap="true" 
                    Width="520px" CellPadding="5" CellSpacing="5"  
                    FieldHeaderStyle-Font-Bold="true" 
                    AutoGenerateEditButton="true" 
                    AutoGenerateDeleteButton="true"
                    OnPageIndexChanging="DVDetalleBitacora_PageIndexChanging" 
                    OnModeChanging="DVDetalleBitacora_ModeChanging" 
                    OnItemUpdating="DVDetalleBitacora_ItemUpdating" 
                    OnItemDeleting="DVDetalleBitacora_ItemDeleting" 
                    OnDataBound="DVDetalleBitacora_DataBound"
                    >
                    <Fields>
                        <asp:BoundField DataField="Id" HeaderText="Id" ReadOnly="true" />
                        <asp:BoundField DataField="Flujo" HeaderText="Flujo:" ReadOnly="true" />
                        <asp:BoundField DataField="TipoTramite" HeaderText="Tipo Trámite:" ReadOnly="true" />
                        <asp:BoundField DataField="Mesa" HeaderText="Mesa:" ReadOnly="true" />
                        <asp:BoundField DataField="Usuario" HeaderText="Usuario:" ReadOnly="true" />
                        <asp:BoundField DataField="FechaInicio" HeaderText="Fecha Inicio:" ReadOnly="true" />
                        <asp:BoundField DataField="FechaTermino" HeaderText="Fecha Término:" ReadOnly="true" />
                        <asp:TemplateField HeaderText="Estado:">
                            <EditItemTemplate>
                                <asp:DropDownList ID="DDLEstado" runat="server">
                                    <asp:ListItem Value="0" Text="Registro"></asp:ListItem>
                                    <asp:ListItem Value="1" Text="Atrapado"></asp:ListItem>
                                    <asp:ListItem Value="2" Text="Hold"></asp:ListItem>
                                    <asp:ListItem Value="3" Text="RevisionHold"></asp:ListItem>
                                    <asp:ListItem Value="4" Text="ReingresoHold"></asp:ListItem>
                                    <asp:ListItem Value="5" Text="SolicitudApoyo"></asp:ListItem>
                                    <asp:ListItem Value="6" Text="ReingresoApoyo"></asp:ListItem>
                                    <asp:ListItem Value="7" Text="Pausa"></asp:ListItem>
                                    <asp:ListItem Value="8" Text="Procesado"></asp:ListItem>
                                    <asp:ListItem Value="9" Text="Rechazo"></asp:ListItem>
                                    <asp:ListItem Value="10" Text="Suspendido"></asp:ListItem>
                                    <asp:ListItem Value="11" Text="RevisionSuspencion"></asp:ListItem>
                                    <asp:ListItem Value="12" Text="ReingresoSuspencion"></asp:ListItem>
                                    <asp:ListItem Value="13" Text="PCI"></asp:ListItem>
                                    <asp:ListItem Value="14" Text="ReingresoPCI"></asp:ListItem>
                                    <asp:ListItem Value="15" Text="RevisionPCI"></asp:ListItem>
                                    <asp:ListItem Value="16" Text="Procesable"></asp:ListItem>
                                    <asp:ListItem Value="17" Text="No Procesable"></asp:ListItem>
                                    <asp:ListItem Value="18" Text="Complementario"></asp:ListItem>
                                    <asp:ListItem Value="19" Text="Revisión con Prospecto"></asp:ListItem>
                                    <asp:ListItem Value="20" Text="Confirmación Pendiente"></asp:ListItem>
                                    <asp:ListItem Value="21" Text="Cita Programada"></asp:ListItem>
                                    <asp:ListItem Value="22" Text="Cita Reprogramada"></asp:ListItem>
                                    <asp:ListItem Value="23" Text="En espera de resultados"></asp:ListItem>
                                    <asp:ListItem Value="24" Text="Información para Citas Medicas"></asp:ListItem>
                                    <asp:ListItem Value="25" Text="Response From Mesa"></asp:ListItem>
                                    <asp:ListItem Value="26" Text="Send To Mesa"></asp:ListItem>
                                    <asp:ListItem Value="27" Text="Revisión Promotoría"></asp:ListItem>
                                    <asp:ListItem Value="28" Text="Revisión Promotoría KO"></asp:ListItem>
                                    <asp:ListItem Value="29" Text="Revisión Promotoría OK"></asp:ListItem>
                                    <asp:ListItem Value="30" Text="Promotoría Cancela"></asp:ListItem>
                                    <asp:ListItem Value="31" Text="Caducado"></asp:ListItem>
                                    <asp:ListItem Value="32" Text="FromMesa"></asp:ListItem>
                                    <asp:ListItem Value="33" Text="Cancelado"></asp:ListItem>
                                    <asp:ListItem Value="34" Text="CPDES"></asp:ListItem>
                                    <asp:ListItem Value="35" Text="Cita Cancelada"></asp:ListItem>
                                    <asp:ListItem Value="36" Text="Promotoria Reconsidera"></asp:ListItem>
                                </asp:DropDownList>
                            </EditItemTemplate>
                            <ItemTemplate>
                                <asp:Label ID="LblObservacion" runat="server" Text='<%# Eval("Estado") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="Observación:">
                            <EditItemTemplate>
                                <asp:TextBox ID="txtObservacion" runat="server" Text='<%# Eval("Observacion") %>' TextMode="MultiLine"></asp:TextBox>
                            </EditItemTemplate>
                            <ItemTemplate>
                                <asp:Label ID="LblObservacion" runat="server" Text='<%# Eval("Observacion") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField> 
                        <asp:TemplateField HeaderText="Observación Privada:">
                            <EditItemTemplate>
                                <asp:TextBox ID="txtObservacionP" runat="server" Text='<%# Eval("ObservacionPrivada") %>' TextMode="MultiLine"></asp:TextBox>
                            </EditItemTemplate>
                            <ItemTemplate>
                                <asp:Label ID="LblObservacionP" runat="server" Text='<%# Eval("ObservacionPrivada") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                    </Fields>
                    <PagerSettings
                        Mode="NextPreviousFirstLast"
                        FirstPageText="[Inicio]"
                        LastPageText="[Última]"
                        NextPageText="[Siguiente]"
                        PreviousPageText="[Anterior]" />

                </asp:DetailsView>


            </asp:Panel>

            <ajaxToolkit:DragPanelExtender ID="DragPanelExtender1" runat="server" TargetControlID="PnlDetalleBitacora" />
            Folio: <asp:TextBox ID="txtIdTramite" runat="server"></asp:TextBox><asp:Button ID="BtnBuscar" runat="server" Text="Buscar" OnClick="BtnBuscar_Click" />
            <asp:RequiredFieldValidator ID="rfvtxtIdTramite" runat="server" ControlToValidate="txtIdTramite" ErrorMessage="*" ForeColor="Red"></asp:RequiredFieldValidator>
            <br /><br />
            <div style="width: 1300px; overflow-y:scroll">
            <asp:GridView ID="GVTramite" runat="server" CellPadding="5" CellSpacing="5" HeaderStyle-Wrap="false" RowStyle-Wrap="false" HeaderStyle-BackColor="#808080" AutoGenerateColumns="false" OnRowCommand="GVTramite_RowCommand">
                <Columns>
                    <asp:BoundField DataField="Id" HeaderText="Id" />
                    <asp:TemplateField HeaderText="Folio">
                        <ItemTemplate>
                            <asp:LinkButton ID="LnkFolio" runat="server" Text='<%# Eval("Folio") %>' CommandArgument='<%# Eval("Folio") + "|" + Eval("Id") %>' CommandName="Accion"></asp:LinkButton>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:BoundField DataField="IdTipoTramite" HeaderText="Id Tipo Trámite" />
                    <asp:BoundField DataField="TipoTramite" HeaderText="Tipo Trámite" />
                    <asp:BoundField DataField="FechaRegistro" HeaderText="Fecha Registro" />
                    <asp:BoundField DataField="FechaTermino" HeaderText="Fecha Término" />
                    <asp:BoundField DataField="Estado" HeaderText="Estado" />
                    <asp:BoundField DataField="statusTramite" HeaderText="Status Trámite" />
                    <asp:BoundField DataField="DatosHtml" HeaderText="Datos Html" />
                    <asp:BoundField DataField="IdPromotoria" HeaderText="Id Promotoría" />
                    <asp:BoundField DataField="IdUsuario" HeaderText="Id Usuario" />
                    <asp:BoundField DataField="AgenteClave" HeaderText="Agente Clave" />
                    <asp:BoundField DataField="NumeroOrden" HeaderText="Número Orden" />
                    <asp:BoundField DataField="FechaSolicitud" HeaderText="Fecha Solicitud" />
                    <asp:BoundField DataField="tipoTramite" HeaderText="Tipo Trámite" />
                    <asp:BoundField DataField="idRamo" HeaderText="Id Ramo" />
                    <asp:BoundField DataField="prioridad" HeaderText="Prioridad" />
                    <asp:BoundField DataField="IdsisLegados" HeaderText="Id Sis Legados" />
                    <asp:BoundField DataField="kwik" HeaderText="Kwik" />
                </Columns>
            </asp:GridView>
            </div>
            <br /><br />
            <div style="width: 1300px; overflow-y:scroll">
            <asp:GridView ID="GVFolio" runat="server" CellPadding="5" CellSpacing="5" HeaderStyle-Wrap="false" HeaderStyle-Font-Bold="false" RowStyle-Wrap="false" AutoGenerateColumns="false" SelectedRowStyle-BackColor="Blue" HeaderStyle-BackColor="#808080">
                <Columns>
                    <asp:BoundField DataField="Id" HeaderText="Id" Visible="false" />
                    <asp:BoundField DataField="IdUsuario" HeaderText="Id Usuario" />
                    <asp:BoundField DataField="usuario" HeaderText="Usuario" />
                    <asp:BoundField DataField="Estado" HeaderText="Tipo Estado" />
                    <asp:BoundField DataField="statusTramite" HeaderText="Status Trámite" />
                    <asp:BoundField DataField="IdTramite" HeaderText="Id Trámite" />
                    <asp:BoundField DataField="FolioTramite" HeaderText="Folio Trámite" />
                    <asp:BoundField DataField="IdMesa" HeaderText="Id Mesa" />
                    <asp:BoundField DataField="Mesa" HeaderText="Mesa" />
                    <asp:BoundField DataField="FechaRegistro" HeaderText="Fecha Registro" />
                    <asp:BoundField DataField="FechaInicio" HeaderText="Fecha Inicio" />
                    <asp:BoundField DataField="FechaFin" HeaderText="Fecha Fin" />
                    <asp:BoundField DataField="ObservacionPublica" HeaderText="Observación Pública" />
                    <asp:BoundField DataField="ObservacionPrivada" HeaderText="Observación Privada" />
                    <asp:BoundField DataField="IdRechazo" HeaderText="Id Rechazo" />
                    <asp:BoundField DataField="Procede" HeaderText="Procede" />
                    <asp:BoundField DataField="AnswerTo" HeaderText="answer To" />
                </Columns>
            </asp:GridView>
            </div>
            <br /><br />
            <div style="width: 1300px; overflow-y:scroll">
            <asp:GridView ID="GVBitacora" runat="server" CellPadding="5" CellSpacing="5" 
                HeaderStyle-Wrap="false" 
                HeaderStyle-Font-Bold="false" 
                RowStyle-Wrap="false" 
                HeaderStyle-BackColor="#808080" 
                AutoGenerateColumns="true" OnRowCommand="GVBitacora_RowCommand" SelectedRowStyle-BackColor="Gray">
                <Columns>
                    <asp:TemplateField>
                        <ItemTemplate>
                            <asp:LinkButton ID="LnkEditarRegistro" runat="server" Text="Editar" CommandArgument='<%# Eval("Id") %>' CommandName="Accion"></asp:LinkButton>
                        </ItemTemplate>
                    </asp:TemplateField>
                </Columns>
            </asp:GridView>
            </div>
            


        </div>
    </form>
</body>
</html>
