//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wfiplib.EnviaCorreos {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EnviaCorreos.IServicioCorreo")]
    public interface IServicioCorreo {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCorreo/TestCorreo", ReplyAction="http://tempuri.org/IServicioCorreo/TestCorreoResponse")]
        string TestCorreo(string pHost, int pPuerto, string pUsuario, string pPassword, string pDestino, string pAsusnto, string pContenido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCorreo/ProcesaCorreo", ReplyAction="http://tempuri.org/IServicioCorreo/ProcesaCorreoResponse")]
        string ProcesaCorreo(string pCorreo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCorreo/ProcesarCorreo", ReplyAction="http://tempuri.org/IServicioCorreo/ProcesarCorreoResponse")]
        string ProcesarCorreo(string para, string de, string titulo, string mensaje);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioCorreoChannel : wfiplib.EnviaCorreos.IServicioCorreo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioCorreoClient : System.ServiceModel.ClientBase<wfiplib.EnviaCorreos.IServicioCorreo>, wfiplib.EnviaCorreos.IServicioCorreo {
        
        public ServicioCorreoClient() {
        }
        
        public ServicioCorreoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioCorreoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioCorreoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioCorreoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string TestCorreo(string pHost, int pPuerto, string pUsuario, string pPassword, string pDestino, string pAsusnto, string pContenido) {
            return base.Channel.TestCorreo(pHost, pPuerto, pUsuario, pPassword, pDestino, pAsusnto, pContenido);
        }
        
        public string ProcesaCorreo(string pCorreo) {
            return base.Channel.ProcesaCorreo(pCorreo);
        }
        
        public string ProcesarCorreo(string para, string de, string titulo, string mensaje) {
            return base.Channel.ProcesarCorreo(para, de, titulo, mensaje);
        }
    }
}
